[button.addRule]
en = "Add rule"
de = "Regel hinzufügen"

[button.adjustRainForecast]
en = "Adjust rain forecast"
de = "Regenvorhersage anpassen"

[button.automatic]
en = "Automatic"
de = "Automatisch"

[button.cancel]
en = "Cancel"
de = "Abbrechen"

[button.confirm]
en = "Confirm"
de = "Bestätigen"

[button.model]
en = "Model"
de = "Modell"

[button.map]
en = "Map"
de = "Karte"

[button.manual]
en = "Manual"
de = "Manuell"

[button.pictures]
en = "Pictures"
de = "Bilder"

[button.semiAutomatic]
en = "Semi-automatic"
de = "Halbautomatisch"

[button.startSimulation]
en = "Start Simulation"
de = "Simulation starten"


[display.module.rrb]
en = "Rain Retention Basin"
de = "Regenrückhaltebecken"


[header.currentValues]
en = "Current Values"
de = "Aktuelle Messwerte"

[header.daySelection]
en = "Daily Course from"
de = "Tagesverlauf vom"

[header.drainage]
en = "Drainage"
de = "Entwässerung"

[header.features]
en = "Features"
de = "Eigenschaften"

[header.rainForecast]
en = "Rain Forecast"
de = "Regenvorhersage"

[header.simulationValues]
en = "Simulation Values"
de = "Simulationswerte"

[header.simulationCourse]
en = "Simulation Course"
de = "Simulationsverlauf"

[header.waterLevel]
en = "Water Level"
de = "Wasserpegel"


[label.applyRainForecast]
en = "Apply rain forecast"
de = "Regenvorhersage übernehmen"

[label.catchmentArea]
en = "Catchment area"
de = "Einzugsgebiet"

[label.chooseTime]
en = "Choose time point"
de = "Zeitpunkt wählen"

[label.city]
en = "City/Municipality"
de = "Stadt/Gemeinde"

[label.drainage.yes]
en = "Draining since"
de = "Entwässern seit"

[label.drainage.no]
en = "No draining"
de = "Keine Entwässerung"

[label.drainageForerun]
en = "Drainage Forerun"
de = "Entwässerungsvorlauf"

[label.latitude]
en = "Latitude"
de = "Breitengrad"

[label.location]
en = "Location"
de = "Standort"

[label.longitude]
en = "Longitude"
de = "Längengrad"

[label.pavedArea]
en = "Paved area"
de = "Befestigte Fläche"

[label.name]
en = "Name"
de = "Name"

[label.rainAmount]
en = "Rain Amount"
de = "Regenmenge"

[label.rainDuration]
en = "Rain Duration"
de = "Regendauer"

[label.rainForecastDate]
en = "Apply forecast from time"
de = "Vorhersage übernehmen vom Zeitpunkt"

[label.retentionVolume]
en = "Retention volume"
de = "Einstauvolumen"

[label.roofSize]
en = "Roof Size"
de = "Dachgröße"

[label.setStartLevel]
en = "Set starting water level"
de = "Startwasserpegel einstellen"

[label.simulationDuration]
en = "Simulation duration"
de = "Simualtionsdauer"

[label.simulationInterval]
en = "Simulation interval"
de = "Simualtionsintervall"

[label.targetLevel]
en = "Target Level"
de = "Zielpegel"

[label.time]
en = "Time"
de = "Zeitpunkt"

[label.title]
en = "Title"
de = "Titel"

[label.unpavedArea]
en = "Unpaved area"
de = "Unbefestigte Fläche"

[notification.success]
en = "No drainage is currently necessary or planned!"
de = "Derzeit keine Entwässerung notwendig und geplant!"


[tab.control]
en = "Control"
de = "Steuerung"

[tab.history]
en = "History"
de = "Historie"

[tab.overview]
en = "Overview"
de = "Übersicht"

[tab.simulation]
en = "Simulation"
de = "Simulation"