[button.addRule]
en = "Add rule"
de = "Regel hinzufügen"

[button.adjustRainForecast]
en = "Adjust rain forecast"
de = "Regenvorhersage anpassen"

[button.cancel]
en = "Cancel"
de = "Abbrechen"

[button.confirm]
en = "Confirm"
de = "Bestätigen"

[button.model]
en = "Model"
de = "Modell"

[button.map]
en = "Map"
de = "Karte"

[button.pictures]
en = "Pictures"
de = "Bilder"

[button.startSimulation]
en = "Start Simulation"
de = "Simulation starten"


[display.module.rrb]
en = "Rain Retention Basin"
de = "Regenrückhaltebecken"


[header.currentValues]
en = "Current Values"
de = "Aktuelle Messwerte"

[header.daySelection]
en = "Daily Course from"
de = "Tagesverlauf vom"

[header.drainage]
en = "Drainage"
de = "Entwässerung"

[header.features]
en = "Features"
de = "Eigenschaften"

[header.rainForecast]
en = "Rain Forecast"
de = "Regenvorhersage"

[header.waterLevel]
en = "Water Level"
de = "Wasserpegel"


[label.drainage.yes]
en = "Draining since"
de = "Entwässern seit"

[label.drainage.no]
en = "No draining"
de = "Keine Entwässerung"

[label.drainageForerun]
en = "Drainage Forerun"
de = "Entwässerungsvorlauf"

[label.location]
en = "Location"
de = "Standort"

[label.rainAmount]
en = "Rain Amount"
de = "Regenmenge"

[label.rainDuration]
en = "Rain Duration"
de = "Regendauer"

[label.rainForecast]
en = "Apply rain forecast"
de = "Regenvorhersage übernehmen"

[label.rainForecastDate]
en = "Apply forecast from time"
de = "Vorhersage übernehmen vom Zeitpunkt"

[label.roofSize]
en = "Roof Size"
de = "Dachgröße"

[label.setStartLevel]
en = "Set starting water level"
de = "Startwasserpegel einstellen"

[label.targetLevel]
en = "Target Level"
de = "Zielpegel"

[label.time]
en = "Time"
de = "Zeitpunkt"

[label.title]
en = "Title"
de = "Titel"


[tab.control]
en = "Control"
de = "Steuerung"

[tab.history]
en = "History"
de = "Historie"

[tab.overview]
en = "Overview"
de = "Übersicht"

[tab.simulation]
en = "Simulation"
de = "Simulation"